# Generated by Django 5.1.1 on 2024-09-30 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_category_name', models.CharField(max_length=20, verbose_name='Bar category name')),
                ('bar_category_description', models.TextField(blank=True, max_length=100, verbose_name='Bar category description')),
                ('is_bar_category_active', models.BooleanField(default=True, verbose_name='Is bar category active')),
                ('bar_category_photo', models.ImageField(blank=True, upload_to='', verbose_name='Bar category photo')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=50, verbose_name='Currency Name')),
                ('currency_code', models.CharField(max_length=3, verbose_name='Currency Code')),
                ('currency_symbol', models.CharField(max_length=5, verbose_name='Currency Symbol')),
            ],
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_category_name', models.CharField(max_length=20, verbose_name='Dish category name')),
                ('dish_category_description', models.TextField(blank=True, max_length=100, verbose_name='Dish category description')),
                ('is_active_dish_category', models.BooleanField(default=True, verbose_name='Is dish category active')),
                ('dish_category_photo', models.ImageField(blank=True, upload_to='', verbose_name='Dish category photo')),
            ],
        ),
        migrations.CreateModel(
            name='BarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_item_name', models.CharField(max_length=20, verbose_name='Bar item name')),
                ('bar_item_description', models.TextField(blank=True, max_length=100, verbose_name='Bar item description')),
                ('bar_item_weight', models.IntegerField(blank=True, null=True, verbose_name='Bar item weight')),
                ('is_allergenic_bar_item', models.BooleanField(default=False, verbose_name='Is bar item allergenic')),
                ('bar_item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bar item price')),
                ('bar_item_cooking_time', models.IntegerField(blank=True, null=True, verbose_name='Bar item cooking time')),
                ('is_active_bar_item', models.BooleanField(default=True, verbose_name='Is bar item active')),
                ('bar_item_photo', models.ImageField(blank=True, upload_to='', verbose_name='Bar item photo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_items', to='promo.barcategory')),
            ],
        ),
        migrations.CreateModel(
            name='DishItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_item_name', models.CharField(max_length=20, verbose_name='Dish item name')),
                ('dish_item_description', models.TextField(blank=True, max_length=100, verbose_name='Dish item description')),
                ('dish_item_weight', models.IntegerField(blank=True, null=True, verbose_name='Dish item weight')),
                ('is_allergenic_dish_item', models.BooleanField(default=False, verbose_name='Is allergenic dish item')),
                ('dish_item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dish item price')),
                ('dish_item_cooking_time', models.IntegerField(blank=True, null=True, verbose_name='Dish item cooking time')),
                ('is_active_dish_item', models.BooleanField(default=True, verbose_name='Is dish item active')),
                ('dish_item_photo', models.ImageField(blank=True, upload_to='', verbose_name='Dish item photo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_items', to='promo.dishcategory')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=255, unique=True, verbose_name='Restaurant name')),
                ('restaurant_address', models.TextField(verbose_name='Restaurant address')),
                ('restaurant_wifi', models.TextField(blank=True, verbose_name='Restaurant wi-fi password')),
                ('restaurant_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo.currency', verbose_name='Restaurant Currency')),
                ('restaurant_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_categories', to='promo.restaurantinfo'),
        ),
        migrations.AddField(
            model_name='barcategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_categories', to='promo.restaurantinfo'),
        ),
    ]
